on:
  push:
    branches:
      - master
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: windows-2019
    env:
      ARCH: x86_64
      TOOLCHAIN: cygwin
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@master
      - shell: powershell
        run: |
          # Download and install Cygwin
          Invoke-WebRequest -Uri https://cygwin.com/setup-${{ env.ARCH }}.exe -OutFile cygwin.exe
          start -Wait .\cygwin.exe '-qng -R cygwin -s http://cygwin.mirror.constant.com -P git -P curl -P gettext -P gcc-core -P gcc-g++ -P cmake -P make -P libpcre-devel -P libcares-devel -P libev-devel -P libsodium-devel -P mbedtls-devel'

          # Run the build script
          .\cygwin\bin\bash.exe -le (Join-Path (Get-Location) build.sh)

      # Upload compiled binaries as artifacts
      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: shadowsocks-libev-${{ env.TOOLCHAIN }}-${{ env.ARCH }}
          path: D:\shadowsocks-builds\shadowsocks-libev-${{ env.TOOLCHAIN }}-${{ env.ARCH }}.tar.gz
